config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :students, only: [:index, :edit, :new, :create, :update, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "manifest.json" => "pwa#manifest", as: :pwa_manifest

  match "*unmatched", to: "application#render_404", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/students") && !req.path.start_with?("/manifest", "/service-worker")
  }

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, format: { with: /\A[^\d]*\z/, message: "only allows letters" }
  validates :marks, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100, message: "must be a number between 0 and 100" }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:edit, :update, :destroy]

  def index
    @student = current_user.students.new
    @students = current_user.students

    if params[:query].present?
      query = params[:query]
      @students = @students.where("name LIKE ? OR subject LIKE ? OR CAST(marks AS TEXT) LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
    end
  
    @students = @students.page(params[:page]).per(9)
  end

  def create
    formatted_name = student_params[:name].split.map(&:capitalize).join(' ')
    formatted_subject = student_params[:subject].split.map(&:capitalize).join(' ')
    @student = current_user.students.find_by(name: formatted_name, subject: formatted_subject)

    if @student
      @student.marks = student_params[:marks].to_i
      if @student.save
        redirect_to user_students_path(current_user), notice: 'Student marks were successfully updated.'
      else
        render :new
      end
    else
      @student = current_user.students.build(student_params.merge({name: formatted_name, subject: formatted_subject}))
      if @student.save
        redirect_to user_students_path(current_user), notice: 'Student was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    if @student.update(student_params)
      redirect_to user_students_path(current_user), notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to user_students_path(current_user), notice: 'Student was successfully deleted.'
  end

  private

  def set_student
    @student = current_user.students.find_by(id: params[:id])
    unless @student
      flash[:alert] = "Student not found."
      redirect_to user_students_path(current_user)
    end
  end

  def student_params
    params.require(:student).permit(:name, :subject, :marks)
  end
end

app/views/students/_form.html.erb
<%= form_for([current_user, @student]) do |f| %>
  <%= render "shared/error_messages", resource: @student  %>

  <%= f.label :name %><br />
  <div class="student-field">
    <%= inline_svg('icons/user.svg', class: 'svg-icon') %>
    <%= f.text_field :name, autofocus: true, class: 'no-border' %>
  </div>

  <%= f.label :subject %><br />
  <div class="student-field">
    <%= inline_svg('icons/text.svg', class: 'svg-icon') %>
    <%= f.text_field :subject, class: 'no-border' %>
  </div>

  <%= f.label :marks %><br />
  <div class="student-field">
    <%= inline_svg('icons/mark.svg', class: 'svg-icon') %>
    <%= f.number_field :marks, class: 'no-border' %>
  </div>

  <div class="actions">
    <%= f.submit @student.new_record? ? "Add" : "Update" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="edit-contailner">
	<div class="edit-main">
		<%= render 'form' %>
	</div>
</div>

app/views/students/index.html.erb
<div class="container_main">

  <%= form_with url: user_students_path(current_user), method: :get, local: true, class: "filter-form" do |f| %>
    <div class="filter-field">
      <%= f.text_field :query, value: params[:query], placeholder: "Search" %>
      <button type="submit" class="filter-button">
        <%= inline_svg('icons/search.svg', class: 'svg-icon') %> 
      </button>
    </div>
  <% end %>

  <div class="container">
    <% if @students.any? %>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Subject</th>
            <th>Mark</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td>
                <div class="profile-initials"><%= student.name[0].upcase %></div>
                <%= student.name%>
              </td>
              <td><%= student.subject.capitalize %></td>
              <td><%= student.marks %></td>
              <td class="action-buttons">
                <%= link_to '#', onclick: "toggleActions('actions-#{student.id}'); event.stopPropagation();", class: 'toggle-button' do %>
                  <%= inline_svg('icons/downcircle.svg', class: 'svg-icon-home') %>
                <% end %>
                <div id="actions-<%= student.id %>" class="action-popup">
                  <%= link_to 'Edit', edit_user_student_path(current_user, student) %>
                  <%= button_to 'Delete', user_student_path(current_user, student), method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>No students found.</p>
    <% end %>
  </div>
  <div>
    <button onclick="openModal()" class="add-button">Add</button>
  </div>
  <%= paginate @students %>
</div>

<div id="addStudentModal" class="modal">
  <div class="modal-content">
    <%= render 'form' if @student %>
  </div>
</div>