config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :students, only: [:index, :edit, :new, :create, :update, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "manifest.json" => "pwa#manifest", as: :pwa_manifest

  match "*unmatched", to: "application#render_404", via: :all, constraints: lambda { |req|
    !req.path.start_with?("/students") && !req.path.start_with?("/manifest", "/service-worker")
  }

  devise_scope :user do
    root "devise/sessions#new"
  end
end

app/views/shared/_error_messages.html.erb
<% if @student.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="navbar-brand">
    <%= link_to 'tailweds.', user_signed_in? ? user_students_path(current_user) : root_path, class: 'navbar-item-logo' %>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', user_signed_in? ? user_students_path(current_user) : root_path, class: 'navbar-item' %>
    </div>

    <div class="navbar-end">
      <% if user_signed_in? %>
      <%= button_to("Logout", destroy_user_session_path, method: :delete, class: 'navbar-item no-style') %>
      <% end %>
    </div>
  </div>
</nav>

